# Generated by Django 5.2.7 on 2025-11-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(unique=True)),
                ('client_port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_info',
            },
        ),
        migrations.CreateModel(
            name='NginxConfigFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_content', models.CharField(max_length=500)),
                ('file_md5', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='nginx_app.clientinfo')),
            ],
            options={
                'db_table': 'nginx_config_file',
            },
        ),
        migrations.CreateModel(
            name='BackendServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_server_addr', models.GenericIPAddressField()),
                ('file_path', models.CharField(max_length=500)),
                ('upstream', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('up', '正常'), ('down', '下线'), ('backup', '备用')], default='up', max_length=10)),
                ('weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_servers', to='nginx_app.clientinfo')),
            ],
            options={
                'db_table': 'backend_server_info',
                'unique_together': {('client', 'backend_server_addr')},
            },
        ),
    ]
