# Generated by Django 5.2.7 on 2025-11-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
        ('nginx_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxconfigfile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='client_app.clientinfo'),
        ),
        migrations.AlterField(
            model_name='backendserverinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_servers', to='client_app.clientinfo'),
        ),
        migrations.DeleteModel(
            name='ClientInfo',
        ),
    ]
