# Generated by Django 5.2.7 on 2025-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='host',
            field=models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='nginx_config_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
